### PR TITLE
Hello microverse project

### PR DESCRIPTION
**Pull request by olanikegloria**
In this Milestone, I introduced the following changes:
I corrected the read me file
I added a licence.md file

### CODE REVIEW

**Review by anagudelogu — CHANGES_REQUESTED** [review]
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @olanikegloria, 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 



## Highlights
✅ Great use of GitHub flow. 💯 
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

### GitHub flow:

- [x] I noticed that you made some changes in a feature branch, but made others directly in the main branch, such as installing linters and updating the README. For future projects, it is important to follow a correct GitHub flow:

image

All the changes should be made in the feature branch, the main branch shouldn't have any direct commits, so we make sure that every piece of code that's in your main branch has passed through a review process and is production-ready! 🤓 🔧 

### Project README:
You did a great job working on your project documentation! 🚀 However, there's still some room to improve!

- [x] Please consider updating the logo in your README file by either adding your own logo (if you have one) or deleting the logo section + template title from the top of the file:

image

- [x] Please also consider removing the link from your `Live demo` section, as of now your project isn't deployed, you can change the link for a "Coming soon" text or similar. Having links that don't work as expected can mislead users browsing your project! 🤓 

image

- [x] Please provide some information about how people can get a local development copy of your project up and running, e.g. Cloning the repo, opening the folder in vscode, and using the `live server` extension to get live updates... This is one of the most important sections of the documentation, especially if multiple people are collaborating. 🤓 

image

- [x] Please make sure that you have a LICENSE and that its respective link in the README is working, you can follow these steps from [GitHub's official docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to set up a LICENSE. Microverse suggests using MIT! 🤓 🔧

Screenshot from 2023-04-25 12-16-12

### Professional Pull Request:

- [x] You did a great job working on a professional PR, however, I think you could add a more detailed description of what you did in the changes you worked on, for example, here's a template: 

```markdown
## In this Milestone, I introduced the following changes:

- Change 1
- Change 2
- ...
```
Please consider editing it! 🤓 🔧 

- [x] Also, for future projects, It would be good to use a better branch name describing the feature you're developing, in this case, `hello-microverse-html` or similar would've been more descriptive. ⚠️  **PLEASE DO NOT TRY TO CHANGE THIS ONE AS IT CAN CAUSE SOME PROBLEMS WITH THE GIT HISTORY, TAKE THIS ADVICE FOR FUTURE MILESTONES!** 🤓 🔧 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by olanikegloria** [comment]
## In this Milestone, I introduced the following changes:

- I corrected the read me file
- I added a licence.md file

**Comment by olanikegloria** [comment]
Please how do I submit again for another code review because I'm done with
the changes

**Review by jmonto55 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED ♻️ 
Hi @olanikegloria 👋🏽, 

Great work on making the changes requested by a previous reviewer 👌
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

AlmostThereGIF
 ## Highlights
✅ Great use of GitHub flow. 💯

 ## Required Changes ♻️
### Professional Pull Request:
- [x] Great job adding a meaningful description to your Pull Request 🤓. However, please kindly make sure that you implement those changes in the Pull Request description, currently your changes were implemented as an extra comment as shown below 👇🏽.


https://user-images.githubusercontent.com/116701485/234435102-333817ff-929f-4ca0-8ff9-ccdecc2d61e2.mp4


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by TuyishimireEric — APPROVED** [review]
# Status: APPROVED 🟢  
### Hi  @olanikegloria  👋 👋 

#### I'm @TuyishimireEric, Your code reviewer,
Good job on implementing the project requirements! 🥇 
done

Your project is complete!  There is nothing else to say other than... it's time to merge it 🦾  
Congratulations! 🎉

## Highlights
✔ Descriptive PR 👍 
✔ The README file is professional and has all the relevant headers 🎆
✔ No linter Error 👍 
### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/enus/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
